export const usersTable = [
    {
      id: 1,
      nombre: 'Usuario 1',
      usuario: 'user1',
      rol: 'Administrador',
      estado: "activo",
      acciones: null,
    },
    {
      id: 2,
      nombre: 'Usuario 2',
      usuario: 'user2',
      rol: 'Tecnico',
      estado: "inactivo",
      acciones: null,
    },
    {
      id: 3,
      nombre: 'Usuario 3',
      usuario: 'user3',
      rol: 'Tecnico',
      estado: "activo",
      acciones: null,
    },
    {
      id: 4,
      nombre: 'Usuario 4',
      usuario: 'user4',
      rol: 'Tecnico',
      estado: "inactivo",
      acciones: null,
    },
    {
      id: 5,
      nombre: 'Usuario 5',
      usuario: 'user5',
      rol: 'Tecnico',
      estado: "activo",
      acciones: null,
    },
    {
        id: 6,
        nombre: 'Usuario 6',
        usuario: 'user1',
        rol: 'Tecnico',
        estado: "activo",
        acciones: null,
      },
      {
        id: 7,
        nombre: 'Usuario 7',
        usuario: 'user2',
        rol: 'Tecnico',
        estado: "inactivo",
        acciones: null,
      },
      {
        id: 8,
        nombre: 'Usuario 8',
        usuario: 'user3',
        rol: 'Tecnico',
        estado: "activo",
        acciones: null,
      },
      {
        id: 9,
        nombre: 'Usuario 9',
        usuario: 'user4',
        rol: 'Tecnico',
        estado: "inactivo",
        acciones: null,
      },
      {
        id: 10,
        nombre: 'Usuario 10',
        usuario: 'user5',
        rol: 'Tecnico',
        estado: "inactivo",
        acciones: null,
      },
      {
        id: 11,
        nombre: 'Usuario 11',
        usuario: 'user1',
        rol: 'Tecnico',
        estado: "activo",
        acciones: null,
      },
      {
        id: 12,
        nombre: 'Usuario 12',
        usuario: 'user2',
        rol: 'Tecnico',
        estado: "inactivo",
        acciones: null,
      },
      {
        id: 13,
        nombre: 'Usuario 13',
        usuario: 'user3',
        rol: 'Tecnico',
        estado: "activo",
        acciones: null,
      },
      {
        id: 14,
        nombre: 'Usuario 4',
        usuario: 'user4',
        rol: 'Tecnico',
        estado: "inactivo",
        acciones: null,
      },
      {
        id: 15,
        nombre: 'Usuario 15',
        usuario: 'user5',
        rol: 'Tecnico',
        estado: "activo",
        acciones: null,
      },
      {
        id: 11,
        nombre: 'Usuario 11',
        usuario: 'user1',
        rol: 'Tecnico',
        estado: "activo",
        acciones: null,
      },
      {
        id: 12,
        nombre: 'Usuario 12',
        usuario: 'user2',
        rol: 'Tecnico',
        estado: "activo",
        acciones: null,
      },
      {
        id: 13,
        nombre: 'Usuario 13',
        usuario: 'user3',
        rol: 'Tecnico',
        estado: "activo",
        acciones: null,
      },
      {
        id: 14,
        nombre: 'Usuario 14',
        usuario: 'user4',
        rol: 'Tecnico',
        estado: "inactivo",
        acciones: null,
      },
      {
        id: 15,
        nombre: 'Usuario 15',
        usuario: 'user5',
        rol: 'Tecnico',
        estado: "activo",
        acciones: null,
      },
];